name: Appointment Booking

on:
  workflow_dispatch:
    inputs:
      mobile_number:
        description: 'Mobile number for booking appointment'
        required: true
      password:
        description: 'Password for booking appointment'
        required: true
      otp:
        description: 'OTP for booking appointment'
        required: true

jobs:
  book-appointment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run appointment booking script
      run: |
        python appointment_booking.py
      env:
        MOBILE_NUMBER: ${{ github.event.inputs.mobile_number }}
        PASSWORD: ${{ github.event.inputs.password }}
        OTP: ${{ github.event.inputs.otp }}
